fix:  Reverting recent change in configure.ac, was failing in WII cross-compile build.
Braking commit: d36545de5631823a86a4e9968698491ea2caf3f5

configure.ac:96: error: possibly undefined macro: AC_CHECK_INCLUDES_DEFAULT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
Error: Process completed with exit code 1.

https://sourceforge.net/p/arki55-fuse-mod/tickets/11/